name: Code Quality

on:
  pull_request:
    branches:
      - production
  # Uncomment and edit the following to run on a schedule.
  # schedule:
  #   - cron: '45 5 * * 0' # Run once per week at 5:45am UTC on Sundays.

jobs:
  code-quality:
    uses: alleyinteractive/.github/.github/workflows/php-code-quality.yml@main
