name: Deploy to Pantheon

on:
  push:
    branches:
      - production
      - preprod
      - develop

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    name: "Build and Deploy to Pantheon"
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install composer dependencies
      uses: alleyinteractive/action-test-php@v1
      with:
        install-command: 'composer install --no-dev --prefer-dist --no-interaction --no-progress'
        php-version: '8.4'
        skip-audit: 'true'
        skip-services: 'true'
        skip-test: 'true'
        skip-wordpress-install: 'true'

    - name: Build
      uses: alleyinteractive/action-test-node@v1
      with:
        node-version: '22'
        skip-audit: 'true'
        skip-test: 'true'

    - name: Deploy to Pantheon
      uses: alleyinteractive/action-deploy-to-pantheon@v2
      with:
        base_directory: './'
        destination_directory: 'wp-content/'
        exclude_list: '.git, .github, .gitmodules, .pantheon, node_modules'
        pantheon_env_name: ${{ github.ref_name }}
        pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        pantheon_site_id: ${{ secrets.PANTHEON_SITE_ID }}
        pantheon_site: ${{ secrets.PANTHEON_SITE }}
        ssh-key: ${{ secrets.REMOTE_REPO_SSH_KEY }}
        autopromote: 'true'

    - name: Notify Slack
      if: always()
      uses: alleyinteractive/action-notify-slack@develop
      with:
        status: ${{ job.status }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
