name: Deploy to VIP Repository

on:
  push:
    branches:
      - production
      - preprod
      - develop

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    name: "Build and Deploy to Pantheon"
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Perform any build steps here. You can leverage the actions provided by Alley.
    # eg.  just installing dependencies here, not running tests.
    # - name: Install composer dependencies
    #   uses: alleyinteractive/action-test-php@develop
    #   with:
    #     php-version: '8.2'
    #     audit-skip: true
    #     install-command: composer update --no-interaction --no-progress && composer dump-autoload
    #     test-skip: true
    #     github-token: ${{ secrets.COMPOSER_ACCESS_TOKEN }}

    - name: Sync to wpcomvip repo
      uses: alleyinteractive/action-deploy-to-remote-repository@develop
      with:
        remote_repo: 'git@github.com:wpcomvip/your-repo-url.git'
        exclude_list: '.git, .gitmodules, node_modules, no-vip'
        ssh-key: ${{ secrets.REMOTE_REPO_SSH_KEY }}
        remote_branch:
          # example: if the branch name is production, set it to master
          # otherwise, use the branch name
          ${{ github.ref_name == 'production' && 'master' || github.ref_name }}

    - name: Notify Slack
      if: always()
      uses: alleyinteractive/action-notify-slack@develop
      with:
        status: ${{ job.status }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}