name: Deploy to Pantheon MultiDev

on:
  push:
    branches:
      - preprod
      - develop

env:
  PANTHEON_SITE: my-cool-site
  PANTHEON_SITE_ID: abc12345-6789-def0-abcd-ef1234567890

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-progress --no-ansi --no-interaction --prefer-dist --no-dev"

      - name: Install npm dependencies
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Sync to Pantheon
        uses: alleyinteractive/action-deploy-to-remote-repository@v1
        with:
          remote_repo: 'ssh://codeserver.dev.${{ env.PANTHEON_SITE_ID }}@codeserver.dev.${{ env.PANTHEON_SITE_ID }}.drush.in:2222/~/repository.git'
          remote_branch: ${{ github.ref_name }}
          destination_directory: 'wp-content/'
          exclude_list: '.git, .github, .gitmodules, node_modules'
          pantheon: 'true'
          ssh-key: ${{ secrets.ALLEY_CI_PANTHEON_SSH_KEY }}
