name: Node Tests

on:
  pull_request:
    branches:
      - production
  schedule:
    - cron: '0 0 * * *'

jobs:
  node-tests:
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      ci: true
      node: 18
      run-audit: true
