name: General Tests

# Tests to be performed on the create-wordpress-project template repository.
# This workflow will be deleted upon configuration.
on:
  # Check on PR to develop branch.
  pull_request:
    branches:
      - production
    types: [opened, synchronize, reopened, ready_for_review]
  # Also check on weekly schedule to catch regressions early.
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  general-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run General Tests
        # See https://github.com/alleyinteractive/action-test-general for more options
        uses: alleyinteractive/action-test-general@develop

      - name: Composer install and make
        uses: alleyinteractive/action-test-php@v1
        with:
          php-version: '8.3'
          github-token: ${{ secrets.COMPOSER_ACCESS_TOKEN}}
          install-command: |
            composer install
            (yes '' || true) | php ./configure.php --project_name="Create WordPress Project" --author_name=Testing --author_email=testing@alley.com
          skip-test: true

      - name: Run Node Tests
        uses: alleyinteractive/action-test-node@v1
        with:
          cache-dependency-path: 'package.json'
          install-command: npm install

      - name: Run PHP Tests
        uses: alleyinteractive/action-test-php@v1
        with:
          php-version: '8.3'
          github-token: ${{ secrets.COMPOSER_ACCESS_TOKEN}}
          skip-install: true
          test-command: |
            composer validate --strict
            # Disabled because phpcs is flagging Alley\WP as a namespace and phpstan fails
            # composer test
