name: General Tests

on:
  # Check on PR to develop branch.
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, ready_for_review]
  # Also check on weekly schedule to catch regressions early.
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  general-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run PHP Tests in src directory
        uses: alleyinteractive/action-test-php@develop
        with:
          php-version: '8.2'
          github-token: ${{ secrets.COMPOSER_ACCESS_TOKEN}}
          install-command: |
            composer install
            (yes '' || true) | php ./configure.php --project_name=cwp --author_name=cwp --author_email=cwp@alley.com
          test-command: |
            composer test