name: Deploy to Pantheon Live

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform build steps
      run: echo "Perform your build steps"

  sync-to-pantheon:
    needs: build
    uses: alleyinteractive/.github/.github/workflows/deploy-to-remote-repository.yml@main
    with:
      remote_repo: 'ssh://codeserver.dev.PANTHEON-SITE-ID@codeserver.dev.PANTHEON-SITE-ID.drush.in:2222/~/repository.git'
      remote_branch: 'master' # Notable that this differs from 'production'
      destination_directory: 'wp-content/'
      exclude_list: '.git, .gitmodules, node_modules'

    secrets:
      REMOTE_REPO_SSH_KEY: ${{ secrets.ALLEY_CI_PANTHEON_SSH_KEY }}

  # To autopromote dev -> test -> live
  deploy-to-pantheon:
    runs-on: ubuntu-latest
    needs: sync-to-pantheon
    steps:
    - name: Install PHP
      run: sudo apt-get install php

    - name: Install Terminus
      run: |
        mkdir -p /tmp/terminus && cd /tmp/terminus
        curl -L https://github.com/pantheon-systems/terminus/releases/download/3.2.1/terminus.phar --output terminus
        chmod +x terminus
        ./terminus self:update
        sudo mv /tmp/terminus/terminus /usr/local/bin/terminus

    - name: Authenticate with Terminus
      run: terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Deploy to Test
      run: |
        terminus env:deploy PANTHEON-SITE-ID.test --note="Deploying from GitHub Actions"
        terminus env:clear-cache PANTHEON-SITE-ID.test

    - name: Deploy to Live
      run: |
        terminus env:deploy PANTHEON-SITE-ID.live --note="Deploying from GitHub Actions"
        # Uncomment to automatically clear cache on live
        #terminus env:clear-cache PANTHEON-SITE-ID.live